// ─────────────────────────────────────────────────────
// DATA: HIRAGANA
// ─────────────────────────────────────────────────────
const H={
"Vokal Dasar":[{c:"あ",r:"a"},{c:"い",r:"i"},{c:"う",r:"u"},{c:"え",r:"e"},{c:"お",r:"o"}],
"Baris K":[{c:"か",r:"ka"},{c:"き",r:"ki"},{c:"く",r:"ku"},{c:"け",r:"ke"},{c:"こ",r:"ko"}],
"Baris S":[{c:"さ",r:"sa"},{c:"し",r:"shi"},{c:"す",r:"su"},{c:"せ",r:"se"},{c:"そ",r:"so"}],
"Baris T":[{c:"た",r:"ta"},{c:"ち",r:"chi"},{c:"つ",r:"tsu"},{c:"て",r:"te"},{c:"と",r:"to"}],
"Baris N":[{c:"な",r:"na"},{c:"に",r:"ni"},{c:"ぬ",r:"nu"},{c:"ね",r:"ne"},{c:"の",r:"no"}],
"Baris H":[{c:"は",r:"ha"},{c:"ひ",r:"hi"},{c:"ふ",r:"fu"},{c:"へ",r:"he"},{c:"ほ",r:"ho"}],
"Baris M":[{c:"ま",r:"ma"},{c:"み",r:"mi"},{c:"む",r:"mu"},{c:"め",r:"me"},{c:"も",r:"mo"}],
"Baris Y":[{c:"や",r:"ya"},{c:"ゆ",r:"yu"},{c:"よ",r:"yo"}],
"Baris R":[{c:"ら",r:"ra"},{c:"り",r:"ri"},{c:"る",r:"ru"},{c:"れ",r:"re"},{c:"ろ",r:"ro"}],
"Baris W + N":[{c:"わ",r:"wa"},{c:"を",r:"wo"},{c:"ん",r:"n"}],
"Dakuten G":[{c:"が",r:"ga"},{c:"ぎ",r:"gi"},{c:"ぐ",r:"gu"},{c:"げ",r:"ge"},{c:"ご",r:"go"}],
"Dakuten Z":[{c:"ざ",r:"za"},{c:"じ",r:"ji"},{c:"ず",r:"zu"},{c:"ぜ",r:"ze"},{c:"ぞ",r:"zo"}],
"Dakuten D":[{c:"だ",r:"da"},{c:"ぢ",r:"ji*"},{c:"づ",r:"zu*"},{c:"で",r:"de"},{c:"ど",r:"do"}],
"Dakuten B":[{c:"ば",r:"ba"},{c:"び",r:"bi"},{c:"ぶ",r:"bu"},{c:"べ",r:"be"},{c:"ぼ",r:"bo"}],
"Handakuten P":[{c:"ぱ",r:"pa"},{c:"ぴ",r:"pi"},{c:"ぷ",r:"pu"},{c:"ぺ",r:"pe"},{c:"ぽ",r:"po"}],
"Combo KY":[{c:"きゃ",r:"kya"},{c:"きゅ",r:"kyu"},{c:"きょ",r:"kyo"}],
"Combo SH":[{c:"しゃ",r:"sha"},{c:"しゅ",r:"shu"},{c:"しょ",r:"sho"}],
"Combo CH":[{c:"ちゃ",r:"cha"},{c:"ちゅ",r:"chu"},{c:"ちょ",r:"cho"}],
"Combo NY":[{c:"にゃ",r:"nya"},{c:"にゅ",r:"nyu"},{c:"にょ",r:"nyo"}],
"Combo HY":[{c:"ひゃ",r:"hya"},{c:"ひゅ",r:"hyu"},{c:"ひょ",r:"hyo"}],
"Combo MY":[{c:"みゃ",r:"mya"},{c:"みゅ",r:"myu"},{c:"みょ",r:"myo"}],
"Combo RY":[{c:"りゃ",r:"rya"},{c:"りゅ",r:"ryu"},{c:"りょ",r:"ryo"}],
"Combo GY":[{c:"ぎゃ",r:"gya"},{c:"ぎゅ",r:"gyu"},{c:"ぎょ",r:"gyo"}],
"Combo JY":[{c:"じゃ",r:"ja"},{c:"じゅ",r:"ju"},{c:"じょ",r:"jo"}],
"Combo BY":[{c:"びゃ",r:"bya"},{c:"びゅ",r:"byu"},{c:"びょ",r:"byo"}],
"Combo PY":[{c:"ぴゃ",r:"pya"},{c:"ぴゅ",r:"pyu"},{c:"ぴょ",r:"pyo"}],
"Vokal Panjang":[{c:"おお",r:"oo",n:"panjang O"},{c:"ええ",r:"ee",n:"panjang E"},{c:"ああ",r:"aa",n:"panjang A"},{c:"いい",r:"ii",n:"panjang I"},{c:"うう",r:"uu",n:"panjang U"}],
"Konsonan Ganda (っ)":[{c:"っか",r:"kka",n:"contoh"},{c:"っさ",r:"ssa",n:"contoh"},{c:"った",r:"tta",n:"contoh"},{c:"っぱ",r:"ppa",n:"contoh"}]
};

// ─── DATA: KATAKANA ───
const K={
"Vokal Dasar":[{c:"ア",r:"a"},{c:"イ",r:"i"},{c:"ウ",r:"u"},{c:"エ",r:"e"},{c:"オ",r:"o"}],
"Baris K":[{c:"カ",r:"ka"},{c:"キ",r:"ki"},{c:"ク",r:"ku"},{c:"ケ",r:"ke"},{c:"コ",r:"ko"}],
"Baris S":[{c:"サ",r:"sa"},{c:"シ",r:"shi"},{c:"ス",r:"su"},{c:"セ",r:"se"},{c:"ソ",r:"so"}],
"Baris T":[{c:"タ",r:"ta"},{c:"チ",r:"chi"},{c:"ツ",r:"tsu"},{c:"テ",r:"te"},{c:"ト",r:"to"}],
"Baris N":[{c:"ナ",r:"na"},{c:"ニ",r:"ni"},{c:"ヌ",r:"nu"},{c:"ネ",r:"ne"},{c:"ノ",r:"no"}],
"Baris H":[{c:"ハ",r:"ha"},{c:"ヒ",r:"hi"},{c:"フ",r:"fu"},{c:"ヘ",r:"he"},{c:"ホ",r:"ho"}],
"Baris M":[{c:"マ",r:"ma"},{c:"ミ",r:"mi"},{c:"ム",r:"mu"},{c:"メ",r:"me"},{c:"モ",r:"mo"}],
"Baris Y":[{c:"ヤ",r:"ya"},{c:"ユ",r:"yu"},{c:"ヨ",r:"yo"}],
"Baris R":[{c:"ラ",r:"ra"},{c:"リ",r:"ri"},{c:"ル",r:"ru"},{c:"レ",r:"re"},{c:"ロ",r:"ro"}],
"Baris W + N":[{c:"ワ",r:"wa"},{c:"ヲ",r:"wo"},{c:"ン",r:"n"}],
"Dakuten G":[{c:"ガ",r:"ga"},{c:"ギ",r:"gi"},{c:"グ",r:"gu"},{c:"ゲ",r:"ge"},{c:"ゴ",r:"go"}],
"Dakuten Z":[{c:"ザ",r:"za"},{c:"ジ",r:"ji"},{c:"ズ",r:"zu"},{c:"ゼ",r:"ze"},{c:"ゾ",r:"zo"}],
"Dakuten D":[{c:"ダ",r:"da"},{c:"ヂ",r:"ji*"},{c:"ヅ",r:"zu*"},{c:"デ",r:"de"},{c:"ド",r:"do"}],
"Dakuten B":[{c:"バ",r:"ba"},{c:"ビ",r:"bi"},{c:"ブ",r:"bu"},{c:"ベ",r:"be"},{c:"ボ",r:"bo"}],
"Handakuten P":[{c:"パ",r:"pa"},{c:"ピ",r:"pi"},{c:"プ",r:"pu"},{c:"ペ",r:"pe"},{c:"ポ",r:"po"}],
"Combo KY":[{c:"キャ",r:"kya"},{c:"キュ",r:"kyu"},{c:"キョ",r:"kyo"}],
"Combo SH":[{c:"シャ",r:"sha"},{c:"シュ",r:"shu"},{c:"ショ",r:"sho"}],
"Combo CH":[{c:"チャ",r:"cha"},{c:"チュ",r:"chu"},{c:"チョ",r:"cho"}],
"Combo NY":[{c:"ニャ",r:"nya"},{c:"ニュ",r:"nyu"},{c:"ニョ",r:"nyo"}],
"Combo HY":[{c:"ヒャ",r:"hya"},{c:"ヒュ",r:"hyu"},{c:"ヒョ",r:"hyo"}],
"Combo MY":[{c:"ミャ",r:"mya"},{c:"ミュ",r:"myu"},{c:"ミョ",r:"myo"}],
"Combo RY":[{c:"リャ",r:"rya"},{c:"リュ",r:"ryu"},{c:"リョ",r:"ryo"}],
"Combo GY":[{c:"ギャ",r:"gya"},{c:"ギュ",r:"gyu"},{c:"ギョ",r:"gyo"}],
"Combo JY":[{c:"ジャ",r:"ja"},{c:"ジュ",r:"ju"},{c:"ジョ",r:"jo"}],
"Combo BY":[{c:"ビャ",r:"bya"},{c:"ビュ",r:"byu"},{c:"ビョ",r:"byo"}],
"Combo PY":[{c:"ピャ",r:"pya"},{c:"ピュ",r:"pyu"},{c:"ピョ",r:"pyo"}],
"Serapan Ti/Di":[{c:"ティ",r:"ti",n:"≈ ti (team)"},{c:"ディ",r:"di",n:"≈ di (disc)"},{c:"テゥ",r:"tu",n:"≈ tu"},{c:"デゥ",r:"du",n:"≈ du"}],
"Serapan WI/WE/WO":[{c:"ウィ",r:"wi"},{c:"ウェ",r:"we"},{c:"ウォ",r:"wo"}],
"Serapan FA/FI/FE/FO":[{c:"ファ",r:"fa"},{c:"フィ",r:"fi"},{c:"フェ",r:"fe"},{c:"フォ",r:"fo"}],
"Serapan VA/VI/VE/VO":[{c:"ヴァ",r:"va"},{c:"ヴィ",r:"vi"},{c:"ヴ",r:"vu"},{c:"ヴェ",r:"ve"},{c:"ヴォ",r:"vo"}],
"Serapan JE/CHE":[{c:"ジェ",r:"je"},{c:"チェ",r:"che"}],
"Vokal Panjang (ー)":[{c:"ケーキ",r:"keeki",n:"kue"},{c:"コーヒー",r:"koohii",n:"kopi"},{c:"ビール",r:"biiru",n:"bir"},{c:"ノート",r:"nooto",n:"buku catatan"}],
"Konsonan Ganda (ッ)":[{c:"ッカ",r:"kka"},{c:"ッサ",r:"ssa"},{c:"ッタ",r:"tta"},{c:"ッパ",r:"ppa"}]
};

// ─── DATA: KOTOBA ───
const KT={
"Hewan":{rows:[
{k:"ねこ",r:"neko",a:"kucing",n:"Kanji: 猫. Hewan peliharaan paling populer di Jepang, sering muncul dalam budaya pop."},
{k:"いぬ",r:"inu",a:"anjing",n:"Kanji: 犬. Lambang tahun anjing dalam kalender zodiak Jepang."},
{k:"きつね",r:"kitsune",a:"rubah",n:"Kanji: 狐. Makhluk mistis dalam mitologi Jepang, dianggap utusan dewa Inari."},
{k:"さかな",r:"sakana",a:"ikan",n:"Kanji: 魚. Awalnya berarti 'teman minum sake' karena ikan sering jadi camilan."},
{k:"にわとり",r:"niwatori",a:"ayam",n:"Kanji: 鶏. Secara harfiah 'burung halaman rumah'."},
{k:"ぞう",r:"zou",a:"gajah",n:"Kanji: 象. Sering ada di kebun binatang Jepang."},
{k:"パンダ",r:"panda",a:"panda",n:"Ditulis katakana karena kata serapan. Panda raksasa dari Cina sangat populer di Jepang."}
]},
"Orang & Keluarga":{rows:[
{k:"わたし",r:"watashi",a:"saya",n:"Kata ganti orang pertama paling netral/formal."},
{k:"あなた",r:"anata",a:"kamu",n:"Terdengar formal; dalam percakapan sehari-hari orang Jepang lebih suka menyebut nama langsung."},
{k:"ひと",r:"hito",a:"orang",n:"Kanji: 人. Kata dasar untuk manusia/orang."},
{k:"せんせい",r:"sensei",a:"guru",n:"Kanji: 先生. Dipakai juga untuk dokter, pengacara, atau siapapun yang ahli di bidangnya."},
{k:"がくせい",r:"gakusei",a:"siswa",n:"Kanji: 学生. Gabungan 学 (belajar) + 生 (orang)."},
{k:"いしゃ",r:"isha",a:"dokter",n:"Kanji: 医者. Disapa dengan 'sensei' dalam percakapan."},
{k:"ともだち",r:"tomodachi",a:"teman",n:"Kanji: 友達. Salah satu kata paling dikenal dari anime/manga."},
{k:"ふたり",r:"futari",a:"dua orang",n:"Kanji: 二人. Cara hitung orang: hitōri (1), futari (2), san-nin (3+)."},
{k:"かぞく",r:"kazoku",a:"keluarga",n:"Kanji: 家族. Gabungan 家 (rumah) + 族 (klan)."},
{k:"こども",r:"kodomo",a:"anak",n:"Kanji: 子供. Hari Anak-anak (Kodomo no Hi) dirayakan 5 Mei."},
{k:"はは",r:"haha",a:"ibu (sendiri)",n:"Dipakai saat membicarakan ibu sendiri kepada orang lain."},
{k:"おかあさん",r:"okaasan",a:"ibu",n:"Dipakai untuk menyapa ibu sendiri atau menyebut ibu orang lain dengan hormat."},
{k:"おとうさん",r:"otousan",a:"ayah",n:"Bentuk hormat. Tanpa 'お' (tousan) lebih santai."},
{k:"おとうと",r:"otouto",a:"adik laki-laki",n:"Untuk menyebut adik sendiri. Untuk adik orang lain pakai 'otouto-san'."},
{k:"おにいさん",r:"oniisan",a:"kakak laki-laki",n:"Bentuk sopan untuk kakak laki-laki orang lain."},
{k:"おねえさん",r:"oneesan",a:"kakak perempuan",n:"Huruf 'ね' digandakan karena vokal panjang."},
{k:"いもうと",r:"imouto",a:"adik perempuan",n:"Untuk menyebut adik sendiri. Untuk adik orang lain tambah '-san'."},
{k:"おばあさん",r:"obaasan",a:"nenek",n:"Perhatikan vokal panjang 'ばあ'. Beda dengan 'obasan' (bibi)."},
{k:"おじいさん",r:"ojiisan",a:"kakek",n:"Vokal panjang 'じい' penting. Beda dengan 'ojisan' (paman)."},
{k:"けいさつ",r:"keisatsu",a:"polisi",n:"Kanji: 警察. Polisi Jepang dikenal ramah; ada koban (pos polisi kecil) di tiap sudut."}
]},
"Tempat":{rows:[
{k:"いえ",r:"ie",a:"rumah",n:"Kanji: 家. Merujuk pada bangunan fisik rumah secara umum."},
{k:"うち",r:"uchi",a:"rumah (sendiri)",n:"Lebih personal dari 'ie'. Juga bisa berarti 'dalam kelompok'."},
{k:"えき",r:"eki",a:"stasiun",n:"Kanji: 駅. Stasiun kereta sangat penting; menjadi pusat komunitas kota."},
{k:"こうえん",r:"kouen",a:"taman",n:"Kanji: 公園. Tempat hanami (melihat bunga sakura) di musim semi."},
{k:"がっこう",r:"gakkou",a:"sekolah",n:"Kanji: 学校. Gabungan 学 (belajar) + 校 (lembaga)."},
{k:"だいがく",r:"daigaku",a:"universitas",n:"Kanji: 大学. Gabungan 大 (besar) + 学 (belajar)."},
{k:"びょういん",r:"byouin",a:"rumah sakit",n:"Kanji: 病院. Jangan tertukar dengan 'biyouin' (美容院) yang berarti salon kecantikan!"},
{k:"くうこう",r:"kuukou",a:"bandara",n:"Kanji: 空港. Gabungan 空 (langit) + 港 (pelabuhan). Harfiah: 'pelabuhan udara'."},
{k:"きっさてん",r:"kissaten",a:"kedai kopi",n:"Kanji: 喫茶店. Kedai kopi tradisional Jepang. Berbeda dengan kafe modern."},
{k:"うみ",r:"umi",a:"laut",n:"Kanji: 海. Jepang negara kepulauan; laut sangat penting dalam budayanya."},
{k:"かわ",r:"kawa",a:"sungai",n:"Kanji: 川. Juga dibaca 'gawa' saat digabung (contoh: Sumida-gawa)."}
]},
"Kendaraan":{rows:[
{k:"でんしゃ",r:"densha",a:"kereta",n:"Kanji: 電車. Gabungan 電 (listrik) + 車 (kendaraan). Kereta listrik, bukan uap."},
{k:"ひこうき",r:"hikouki",a:"pesawat",n:"Kanji: 飛行機. Gabungan 飛 (terbang) + 行 (pergi) + 機 (mesin)."},
{k:"くるま",r:"kuruma",a:"mobil",n:"Kanji: 車. Kata yang sama untuk 'kendaraan beroda' secara umum."},
{k:"じてんしゃ",r:"jitensha",a:"sepeda",n:"Kanji: 自転車. Gabungan 自 (sendiri) + 転 (berputar) + 車 (roda)."},
{k:"のりもの",r:"norimono",a:"kendaraan",n:"Kanji: 乗り物. Gabungan 乗り (naik) + 物 (benda). Harfiah: 'benda yang dinaiki'."}
]},
"Makanan & Minuman":{rows:[
{k:"たまご",r:"tamago",a:"telur",n:"Kanji: 卵. Dari kata kuno 'tama' (bulat) + 'ko' (anak). Artinya 'anak berbentuk bulat'."},
{k:"みかん",r:"mikan",a:"jeruk mandarin",n:"Buah khas musim dingin Jepang. Sering dimakan di bawah kotatsu."},
{k:"りんご",r:"ringo",a:"apel",n:"Kanji: 林檎. Apel Aomori terkenal sebagai yang terbaik di Jepang."},
{k:"じゃがいも",r:"jagaimo",a:"kentang",n:"Dari 'Jaga' (Jakarta/Batavia) + 'imo' (ubi). Kentang dibawa dari Indonesia ke Jepang!"},
{k:"たべもの",r:"tabemono",a:"makanan",n:"Kanji: 食べ物. Gabungan 食べ (makan) + 物 (benda)."},
{k:"ごはん",r:"gohan",a:"nasi / makan",n:"Kanji: 御飯. Prefiks sopan 'go' + 'han' (nasi). Bisa berarti nasi matang atau waktu makan."},
{k:"おちゃ",r:"ocha",a:"teh hijau",n:"Kanji: お茶. Teh hijau adalah minuman nasional Jepang."},
{k:"こうちゃ",r:"koucha",a:"teh hitam",n:"Kanji: 紅茶. Harfiah: 'teh merah'."},
{k:"ジュース",r:"juusu",a:"jus",n:"Serapan 'juice'. Ditulis katakana karena gairaigo (kata asing)."},
{k:"カレー",r:"karee",a:"kari",n:"Serapan 'curry'. Kari Jepang (wa-fu karee) lebih manis dan kental dari kari India."},
{k:"サンドイッチ",r:"sandoicchi",a:"sandwich",n:"Serapan 'sandwich'. 'ッチ' untuk bunyi konsonan ganda 'tch'."}
]},
"Benda":{rows:[
{k:"ほん",r:"hon",a:"buku",n:"Kanji: 本. Juga berarti 'asal/asli' (nihon = Jepang)."},
{k:"じしょ",r:"jisho",a:"kamus",n:"Kanji: 辞書. Gabungan 辞 (kata) + 書 (tulisan)."},
{k:"かみ",r:"kami",a:"kertas",n:"Kanji: 紙. Waspada homofon: 'kami' juga berarti 'rambut' (髪) dan 'dewa' (神)!"},
{k:"ノート",r:"nooto",a:"buku catatan",n:"Serapan 'note'. Vokal panjang ditandai 'ー' dalam katakana."},
{k:"かぎ",r:"kagi",a:"kunci",n:"Kanji: 鍵. 'Kagi kakko' = tanda kurung siku [ ]."},
{k:"とけい",r:"tokei",a:"jam",n:"Kanji: 時計. Gabungan 時 (waktu) + 計 (mengukur)."},
{k:"かさ",r:"kasa",a:"payung",n:"Kanji: 傘. Ada budaya 'kasa no wasuremono' (payung tertinggal) di stasiun."},
{k:"つくえ",r:"tsukue",a:"meja belajar",n:"Kanji: 机. Khusus meja belajar/kerja. Meja makan = 'teburu' (テーブル)."},
{k:"でんわ",r:"denwa",a:"telepon",n:"Kanji: 電話. Gabungan 電 (listrik) + 話 (bicara)."},
{k:"いす",r:"isu",a:"kursi",n:"Kanji: 椅子. Kata asli Jepang untuk tempat duduk berkaki."},
{k:"ベッド",r:"beddo",a:"tempat tidur",n:"Serapan 'bed'. Konsonan ganda 'dd' ditulis 'ッド'."},
{k:"ふとん",r:"futon",a:"futon",n:"Kanji: 布団. Kasur lipat tradisional. Kata 'futon' sudah masuk kosakata Inggris!"},
{k:"まくら",r:"makura",a:"bantal",n:"Kanji: 枕. Ada tradisi 'makura-gaeshi' dalam cerita hantu Jepang."},
{k:"ドア",r:"doa",a:"pintu",n:"Serapan 'door'. Pintu geser tradisional disebut 'shoji' atau 'fusuma'."},
{k:"まど",r:"mado",a:"jendela",n:"Kanji: 窓. 'Mado-guchi' (窓口) = loket/counter layanan."},
{k:"きっぷ",r:"kippu",a:"tiket",n:"Kanji: 切符. Gabungan 切 (memotong) + 符 (tanda)."}
]},
"Benda (di Kelas)":{rows:[
{k:"エアコン",r:"eakon",a:"AC / pendingin ruangan",n:"Serapan 'air conditioner' disingkat. Di Jepang hampir semua kelas dan kantor punya eakon — musim panasnya sangat terik."},
{k:"エアコンのリモコン",r:"eakon no rimokon",a:"remote AC",n:"Rimokon = serapan 'remote control'. Kombinasi eakon (AC) + no (partikel milik) + rimokon (remote). Di Jepang remote AC sering diperebutkan di kelas!"},
{k:"ほん",r:"hon",a:"buku",n:"Kanji: 本. Sudah ada di sub-bab Benda umum, tapi konteks kelas sangat relevan — buku pelajaran, buku teks."},
{k:"ノート",r:"nooto",a:"buku catatan",n:"Serapan 'note'. Di Jepang nooto-taking sangat serius; ada seni khusus menulis catatan yang rapi (bisa juga beli buku catatan premium)."},
{k:"ボールペン",r:"boorupen",a:"pulpen / ballpoint",n:"Serapan 'ball pen'. Disingkat dari ballpoint pen. Salah satu alat tulis paling umum di kelas Jepang."},
{k:"ボトル",r:"botoru",a:"botol minum",n:"Serapan 'bottle'. Di banyak sekolah Jepang, siswa membawa botol minum sendiri dari rumah."},
{k:"カーテン",r:"kaaten",a:"gorden / tirai",n:"Serapan 'curtain'. Di kelas Jepang, gorden sering dipakai untuk mengatur cahaya saat menonton proyektor atau saat panas."},
{k:"はさみ",r:"hasami",a:"gunting",n:"Kanji: 鋏. Alat tulis wajib di kelas. Beda dengan キッチンばさみ (gunting dapur) — ini hasami biasa untuk kertas."},
{k:"けいたいでんわ",r:"keitai denwa",a:"handphone",n:"Kanji: 携帯電話. Harfiah: 'telepon yang dibawa-bawa'. Biasa disingkat 'keitai'. Di sekolah Jepang umumnya dilarang atau wajib disimpan saat pelajaran."},
{k:"とけい",r:"tokei",a:"jam dinding",n:"Kanji: 時計. Sudah ada di Benda umum. Di kelas biasanya ada jam dinding besar di depan."},
{k:"まど",r:"mado",a:"jendela",n:"Kanji: 窓. Sudah ada di Benda umum. Di kelas Jepang biasanya punya jendela besar di sisi kiri (cahaya dari kiri untuk penulis tangan kanan)."},
{k:"じしゃ",r:"jisha",a:"penghapus (karet)",n:"Kanji: 字消し / 消しゴム lebih umum. 'Ji' (huruf/tulisan) + 'sha' (menghapus). Penghapus karet untuk pensil."},
{k:"くつした",r:"kutushita",a:"kaos kaki",n:"Kanji: 靴下. Kutsu (sepatu) + Shita (bawah). Harfiah: 'yang di bawah sepatu'. Di sekolah Jepang yang pakai indoor shoes, kaos kaki sangat penting."},
{k:"チョーク",r:"chooku",a:"kapur tulis",n:"Serapan 'chalk'. Dipakai di papan tulis hitam (kokuban). Meski banyak sekolah beralih ke whiteboard, chooku masih umum."},
{k:"かみ",r:"kami",a:"kertas",n:"Kanji: 紙. Sudah ada di Benda umum. Di kelas konteksnya: kertas soal, kertas tugas, kertas origami."},
{k:"せんぷうき",r:"senpuuki",a:"kipas angin",n:"Kanji: 扇風機. Sen (kipas) + Fuu (angin) + Ki (mesin). Di kelas yang belum punya AC, senpuuki jadi penyelamat di musim panas."},
{k:"コンピュータ",r:"konpyuuta",a:"komputer",n:"Serapan 'computer'. Untuk komputer desktop di lab komputer sekolah. Sehari-hari lebih sering disebut 'pasokon'."},
{k:"ふでばこ",r:"fudebako",a:"tempat pensil / kotak pensil",n:"Kanji: 筆箱. Fude (kuas/pena) + Hako/Bako (kotak). Di Jepang fudebako bisa sangat elaborate — ada yang multi-layer dengan cermin kecil di dalam!"},
{k:"パソコン",r:"pasokon",a:"laptop / PC",n:"Singkatan dari 'personal computer' dalam pengucapan Jepang. Lebih umum dari 'konpyuuta' untuk percakapan sehari-hari."},
{k:"つくえ",r:"tsukue",a:"meja (belajar)",n:"Kanji: 机. Sudah ada di Benda umum. Di kelas Jepang, meja siswa biasanya kecil dan individual, bukan meja panjang."},
{k:"こくばん",r:"kokuban",a:"papan tulis hitam",n:"Kanji: 黒板. Koku (hitam) + Ban (papan). Harfiah: 'papan hitam'. Dibersihkan dengan kokuban keshi. Piket membersihkan kokuban adalah tugas umum siswa Jepang."},
{k:"ホワイトボード",r:"howaitoboodo",a:"whiteboard",n:"Serapan 'whiteboard'. Mulai banyak menggantikan kokuban di sekolah dan kantor modern Jepang."},
{k:"けしごむ",r:"keshigomu",a:"penghapus karet",n:"Kanji: 消しゴム. Keshi (menghapus) + Gomu (dari Belanda 'gom' = karet). Harfiah: 'karet penghapus'. Lebih umum dari 'jisha'."},
{k:"こくばんけし",r:"kokuban keshi",a:"penghapus papan tulis",n:"Kanji: 黒板消し. Kokuban (papan hitam) + Keshi (penghapus). Penghapus bulu/spons khusus untuk membersihkan kokuban. Membersihkan ini adalah tugas piket klasik."},
{k:"えんぴつ",r:"enpitsu",a:"pensil",n:"Kanji: 鉛筆. En (timah/logam) + Pitsu (dari Portugis 'pito' = pipa). Harfiah: 'pipa timah'. Di Jepang pensil kayu masih sangat umum di sekolah dasar."},
{k:"ちず",r:"chizu",a:"peta",n:"Kanji: 地図. Chi (bumi/tanah) + Zu (gambar/diagram). Harfiah: 'gambar bumi'. Ada di kelas pelajaran geografi dan IPS."},
{k:"ほうき",r:"houki",a:"sapu",n:"Kanji: 箒. Di sekolah Jepang, siswa sendiri yang membersihkan kelas — tidak ada petugas kebersihan. Houki adalah alat piket wajib."},
{k:"くつ",r:"kutsu",a:"sepatu",n:"Kanji: 靴. Di sekolah Jepang ada sistem 'indoor shoes' (uwabaki) — sepatu luar dilepas di pintu masuk, ganti sandal khusus dalam ruangan."},
{k:"かばん",r:"kaban",a:"tas",n:"Kanji: 鞄. Tas sekolah. Di Jepang siswa SD pakai 'randoseru' (ransel kaku khas Jepang). SMP/SMA pakai kaban biasa."},
{k:"ゴミばこ",r:"gomibako",a:"tempat sampah",n:"Kanji: ゴミ箱. Sudah ada di Perabot Dapur. Di kelas Jepang biasanya ada beberapa gomibako untuk memisahkan sampah (daur ulang, organik, dll)."},
{k:"ティッシュボックス",r:"tisshu bokkusu",a:"kotak tisu",n:"Serapan 'tissue box'. Di Jepang ada tisu khusus (pocketissue) yang sering dibagikan gratis sebagai promosi di jalanan!"},
{k:"いす",r:"isu",a:"kursi",n:"Kanji: 椅子. Sudah ada di Benda umum. Di kelas Jepang, kursi biasanya individual dan bisa diatur posisinya saat kerja kelompok."},
{k:"めがね",r:"megane",a:"kacamata",n:"Kanji: 眼鏡. Me (mata) + Kane/Gane (logam). Harfiah: 'logam untuk mata'. Di budaya pop Jepang, karakter berkacamata sering digambarkan sebagai pintar atau serius ('megane chara')."},
{k:"カレンダー",r:"karendaa",a:"kalender",n:"Serapan 'calendar'. Di kelas biasanya ada di dinding depan atau belakang. Kalender Jepang sering mencantumkan tahun era Jepang (Reiwa, dll) selain tahun Masehi."},
{k:"マーカー",r:"maakaa",a:"spidol / marker",n:"Serapan 'marker'. Dipakai untuk whiteboard atau menandai teks. Ada juga 'keikoo pen' (蛍光ペン) = highlighter/stabilo."},
{k:"えんぴつけずり",r:"enpitsu kezuri",a:"rautan pensil",n:"Kanji: 鉛筆削り. Enpitsu (pensil) + Kezuri (mengikis/meraut). Harfiah: 'peraut pensil'. Di Jepang ada yang manual dan elektrik."},
{k:"プロジェクター",r:"purojekutaa",a:"proyektor",n:"Serapan 'projector'. Makin umum di sekolah Jepang modern, sering dipasang di langit-langit kelas."},
{k:"ものさし / じょうぎ",r:"monosashi / jougi",a:"penggaris",n:"Kanji: 物差し / 定規. Monosashi (物差し) = penggaris untuk mengukur. Jougi (定規) = penggaris untuk menggaris lurus. Secara praktis dipakai bergantian."},
{k:"スピーカー",r:"supiikaa",a:"speaker",n:"Serapan 'speaker'. Di kelas untuk pengumuman sekolah lewat PA system, atau untuk pelajaran bahasa dengan audio."},
{k:"でんたく",r:"dentaku",a:"kalkulator",n:"Kanji: 電卓. Den (listrik) + Taku (meja kecil/tablet). Harfiah: 'tablet listrik'. Di Jepang kalkulator diperbolehkan di beberapa ujian tertentu."},
{k:"もんだな",r:"mondana",a:"rak buku / lemari kelas",n:"Tempat menyimpan buku dan perlengkapan di kelas. Setiap siswa Jepang biasanya punya laci/rak sendiri di kelas."},
{k:"モップ",r:"moppu",a:"mop / pel",n:"Serapan 'mop'. Dipakai saat piket membersihkan lantai kelas. Di Jepang siswa secara bergilir melakukan souji (掃除) = piket kebersihan."},
{k:"はたき",r:"hataki",a:"kemoceng",n:"Kanji: 叩き/はたき. Alat untuk mengibaskan debu dari permukaan. Dipakai saat piket membersihkan rak dan perabot kelas."},
{k:"のり",r:"nori",a:"lem",n:"Kanji: 糊. Lem kertas. Jangan tertukar dengan のり (海苔) yang berarti rumput laut! Beda kanji, beda makna, pengucapan sama."}
]},
"Alam":{rows:[
{k:"みず",r:"mizu",a:"air",n:"Kanji: 水. Khusus air dingin/biasa. Air panas = 'oyu' (お湯)."},
{k:"はな",r:"hana",a:"bunga",n:"Kanji: 花. Waspada homofon: 'hana' juga bisa berarti 'hidung' (鼻)!"}
]},
"Kata Sifat":{rows:[
{k:"たかい",r:"takai",a:"mahal / tinggi",n:"Dua arti berbeda, satu kata! Konteks menentukan makna."},
{k:"はやい",r:"hayai",a:"cepat",n:"Kanji: 速い. Ada 'hayai' (早い) yang berarti 'pagi/lebih awal'. Beda kanji, beda makna."},
{k:"おそい",r:"osoi",a:"lambat",n:"Kanji: 遅い. Lawan kata dari 'hayai'. Juga berarti 'terlambat'."},
{k:"おおきな",r:"ookina",a:"besar",n:"Bentuk na-adjective. Ada juga 'ookii' (大きい) sebagai i-adjective."},
{k:"ちいさい",r:"chiisai",a:"kecil",n:"Kanji: 小さい. Vokal panjang 'ちい'. Lawan kata dari 'ookii'."},
{k:"うれしい",r:"ureshii",a:"senang",n:"Kanji: 嬉しい. Senang karena sesuatu terjadi. Beda dengan 'tanoshii' (menyenangkan)."},
{k:"かなしい",r:"kanashii",a:"sedih",n:"Kanji: 悲しい. Banyak muncul dalam lagu dan puisi Jepang."}
]},
"Musim":{rows:[
{k:"はる",r:"haru",a:"musim semi",n:"Kanji: 春. Musim sakura. Tahun ajaran/kerja Jepang dimulai April."},
{k:"なつ",r:"natsu",a:"musim panas",n:"Kanji: 夏. Musim festival (matsuri) dan kembang api (hanabi)."},
{k:"あき",r:"aki",a:"musim gugur",n:"Kanji: 秋. Musim daun merah (koyo) dan panen."},
{k:"ふゆ",r:"fuyu",a:"musim dingin",n:"Kanji: 冬. Musim salju. Natal dan tahun baru paling meriah."}
]},
"Kata Kerja":{rows:[
{k:"いきます",r:"ikimasu",a:"pergi",n:"Dari 'iku'. Partikel 'ni' atau 'e' menunjukkan tujuan."},
{k:"きます",r:"kimasu",a:"datang",n:"Dari 'kuru' (tidak beraturan). Arah menuju pembicara."},
{k:"かえります",r:"kaerimasu",a:"pulang",n:"Dari 'kaeru'. Khusus pulang ke rumah/tempat asal."},
{k:"でます",r:"demasu",a:"keluar",n:"Dari 'deru'. Juga berarti 'muncul' atau 'berangkat' (kereta)."},
{k:"はいります",r:"hairimasu",a:"masuk",n:"Dari 'hairu'. Partikel 'ni' dipakai untuk tempat yang dimasuki."},
{k:"たべます",r:"tabemasu",a:"makan",n:"Dari 'taberu'. Diikuti objek dengan partikel 'wo'."},
{k:"のみます",r:"nomimasu",a:"minum",n:"Dari 'nomu'. Minum obat juga pakai kata ini."},
{k:"みます",r:"mimasu",a:"melihat / menonton",n:"Dari 'miru'. Menonton film = eiga wo mimasu."},
{k:"ききます",r:"kikimasu",a:"mendengar",n:"Dari 'kiku'. Juga berarti 'bertanya' (sensei ni kikimasu)."},
{k:"はなします",r:"hanashimasu",a:"berbicara",n:"Dari 'hanasu'. 'Hanashi' = cerita/pembicaraan."},
{k:"よみます",r:"yomimasu",a:"membaca",n:"Dari 'yomu'. Hon wo yomimasu = membaca buku."},
{k:"かきます",r:"kakimasu",a:"menulis",n:"Dari 'kaku'. Juga berarti 'menggambar' atau 'melukis'."},
{k:"およぎます",r:"oyogimasu",a:"berenang",n:"Dari 'oyogu'. Kata kerja baris G."},
{k:"あそびます",r:"asobimasu",a:"bermain",n:"Dari 'asobu'. Orang dewasa juga pakai kata ini untuk bersenang-senang."},
{k:"すわります",r:"suwarimasu",a:"duduk",n:"Dari 'suwaru'."},
{k:"たちます",r:"tachimasu",a:"berdiri",n:"Dari 'tatsu'. Juga berarti 'muncul' secara kiasan."},
{k:"しています",r:"shiteimasu",a:"sedang melakukan",n:"Bentuk 'te-iru' menyatakan aksi sedang berlangsung."},
{k:"あります",r:"arimasu",a:"ada (benda mati)",n:"Dari 'aru'. Khusus benda mati/tidak bergerak."},
{k:"います",r:"imasu",a:"ada (makhluk hidup)",n:"Dari 'iru'. Untuk manusia dan hewan."}
]},
"Konsep Umum":{rows:[
{k:"やすみ",r:"yasumi",a:"libur / istirahat",n:"Kanji: 休み. 'O-yasumi nasai' = selamat malam (harfiah: istirahatlah)."},
{k:"けいかく",r:"keikaku",a:"rencana",n:"Kanji: 計画. Gabungan 計 (mengukur) + 画 (rencana)."},
{k:"せいかつ",r:"seikatsu",a:"kehidupan",n:"Kanji: 生活. Gabungan 生 (hidup) + 活 (aktif). Kehidupan sehari-hari."},
{k:"せかい",r:"sekai",a:"dunia",n:"Kanji: 世界. Sering muncul dalam judul anime!"},
{k:"ちしき",r:"chishiki",a:"pengetahuan",n:"Kanji: 知識. Gabungan 知 (mengetahui) + 識 (mengenali)."},
{k:"けつえき",r:"ketsueki",a:"darah",n:"Kanji: 血液. Di Jepang ada kepercayaan golongan darah menentukan kepribadian."}
]},
"Angka":{rows:[
{k:"いち",r:"ichi",a:"1",n:"Kanji: 一. Dasar sistem angka Jepang."},
{k:"に",r:"ni",a:"2",n:"Kanji: 二. Juga partikel 'ni' (ke/di), tapi beda konteks."},
{k:"さん",r:"san",a:"3",n:"Kanji: 三. Juga sapaan hormat '-san', tapi ini angka!"},
{k:"よん / し",r:"yon / shi",a:"4",n:"'Shi' dihindari karena homofon dengan 死 (mati). 'Yon' lebih umum."},
{k:"ご",r:"go",a:"5",n:"Kanji: 五."},
{k:"ろく",r:"roku",a:"6",n:"Kanji: 六."},
{k:"なな / しち",r:"nana / shichi",a:"7",n:"'Shichi' mirip 'ichi' sehingga sering dipakai 'nana'."},
{k:"はち",r:"hachi",a:"8",n:"Kanji: 八. Angka keberuntungan di Jepang (kanji melebar ke bawah = kemakmuran)."},
{k:"きゅう / く",r:"kyuu / ku",a:"9",n:"'Ku' dihindari karena homofon dengan 苦 (penderitaan)."},
{k:"じゅう",r:"juu",a:"10",n:"Kanji: 十."},
{k:"ひゃく",r:"hyaku",a:"100",n:"Kanji: 百."},
{k:"せん",r:"sen",a:"1.000",n:"Kanji: 千."},
{k:"まん",r:"man",a:"10.000",n:"Kanji: 万. Sistem angka Jepang berkelompok per 10.000."},
{k:"おく",r:"oku",a:"100.000.000",n:"Kanji: 億. Seratus juta."},
{k:"ちょう",r:"chou",a:"1 triliun",n:"Kanji: 兆. Anggaran negara Jepang sering dinyatakan dalam satuan ini."}
]},
"Waktu":{rows:[
{k:"じ",r:"ji",a:"jam",n:"Kanji: 時. Penanda jam. ichiji = jam 1, niji = jam 2, dst."},
{k:"ふん / ぷん",r:"fun / pun",a:"menit",n:"Bacaan berubah tergantung angka: 1=ippun, 3=sanpun, 6=roppun."},
{k:"びょう",r:"byou",a:"detik",n:"Kanji: 秒."},
{k:"ごぜん",r:"gozen",a:"AM",n:"Kanji: 午前. Sebelum tengah hari."},
{k:"ごご",r:"gogo",a:"PM",n:"Kanji: 午後. Setelah tengah hari."},
{k:"いま",r:"ima",a:"sekarang",n:"Kanji: 今. 'Ima nanji?' = Sekarang jam berapa?"},
{k:"はん",r:"han",a:"setengah (jam)",n:"ichiji han = jam 1:30."},
{k:"あさ",r:"asa",a:"pagi",n:"Kanji: 朝."},
{k:"ひる",r:"hiru",a:"siang",n:"Kanji: 昼. 'Hirune' = tidur siang."},
{k:"ゆうがた",r:"yuugata",a:"sore",n:"Kanji: 夕方. Sore menjelang malam (~17-18:00)."},
{k:"よる",r:"yoru",a:"malam",n:"Kanji: 夜."},
{k:"ばん",r:"ban",a:"malam (santai)",n:"Kanji: 晩. 'Konban wa' = Selamat malam."},
{k:"よなか",r:"yonaka",a:"tengah malam",n:"Kanji: 夜中."},
{k:"しんや",r:"shinya",a:"larut malam",n:"Kanji: 深夜. Lebih larut dari 'yonaka'."}
]},
"Durasi":{rows:[
{k:"いちじかん",r:"ichi jikan",a:"selama 1 jam",n:"Kanji: 一時間. Ichi (1) + Ji (jam) + Kan (interval/selama). Pola: angka + じかん untuk durasi jam."},
{k:"にじかん",r:"ni jikan",a:"selama 2 jam",n:"Kanji: 二時間. に (2) + じかん."},
{k:"さんじかん",r:"san jikan",a:"selama 3 jam",n:"Kanji: 三時間. さん (3) + じかん."},
{k:"いちにちかん",r:"ichi nichikan",a:"selama 1 hari",n:"Kanji: 一日間. Juga cukup pakai いちにち (ichinichi) tanpa かん. Perhatikan: ini DURASI (selama sehari penuh), beda dengan ついたち yang berarti tanggal 1."},
{k:"ふつかかん",r:"futsukakan",a:"selama 2 hari",n:"Kanji: 二日間. Menarik — pola hitungan hari untuk durasi sama dengan tanggal (futsuka, mikka, yokka, dst) + かん."},
{k:"みっかかん",r:"mikkakan",a:"selama 3 hari",n:"Kanji: 三日間. みっか (3 hari) + かん."},
{k:"いっしゅうかん",r:"isshuukan",a:"selama 1 minggu",n:"Kanji: 一週間. Isshuukan adalah bentuk baku — huruf っ muncul karena ichi + shuu mengalami perubahan bunyi. Kata ini sangat sering dipakai!"},
{k:"にしゅうかん",r:"nishuukan",a:"selama 2 minggu",n:"Kanji: 二週間. に (2) + しゅうかん."},
{k:"さんしゅうかん",r:"sanshuukan",a:"selama 3 minggu",n:"Kanji: 三週間. さん (3) + しゅうかん."},
{k:"いっかげつ",r:"ikkagetsu",a:"selama 1 bulan",n:"Kanji: 一か月. Perhatikan perubahannya: ichi + kagetsu → ikkagetsu (konsonan ganda). Berbeda dengan ichigatsu (Januari) yang menyebut nama bulan."},
{k:"にかげつ",r:"nikagetsu",a:"selama 2 bulan",n:"Kanji: 二か月. に (2) + かげつ."},
{k:"さんかげつ",r:"sankagetsu",a:"selama 3 bulan",n:"Kanji: 三か月. さん (3) + かげつ."},
{k:"いちねんかん",r:"ichinenkan",a:"selama 1 tahun",n:"Kanji: 一年間. Ichi (1) + Nen (tahun) + Kan (interval). Juga bisa cukup いちねん (ichininen) tanpa かん dalam percakapan santai."},
{k:"にねんかん",r:"ninenkan",a:"selama 2 tahun",n:"Kanji: 二年間. に (2) + ねんかん."}
]},
"Hari dalam Seminggu":{rows:[
{k:"げつようび",r:"getsuyoubi",a:"Senin",n:"Kanji: 月曜日. 月 = bulan. Hari bulan."},
{k:"かようび",r:"kayoubi",a:"Selasa",n:"Kanji: 火曜日. 火 = api. Hari api."},
{k:"すいようび",r:"suiyoubi",a:"Rabu",n:"Kanji: 水曜日. 水 = air. Hari air."},
{k:"もくようび",r:"mokuyoubi",a:"Kamis",n:"Kanji: 木曜日. 木 = pohon. Hari kayu."},
{k:"きんようび",r:"kinyoubi",a:"Jumat",n:"Kanji: 金曜日. 金 = emas. Hari emas."},
{k:"どようび",r:"doyoubi",a:"Sabtu",n:"Kanji: 土曜日. 土 = tanah. Hari tanah."},
{k:"にちようび",r:"nichiyoubi",a:"Minggu",n:"Kanji: 日曜日. 日 = matahari. Hari matahari."}
]},
"Keterangan Hari":{rows:[
{k:"きょう",r:"kyou",a:"hari ini",n:"Kanji: 今日."},
{k:"あした",r:"ashita",a:"besok",n:"Kanji: 明日. Juga bisa 'asu' (lebih formal)."},
{k:"あさって",r:"asatte",a:"lusa",n:"Kanji: 明後日."},
{k:"きのう",r:"kinou",a:"kemarin",n:"Kanji: 昨日."},
{k:"おととい",r:"ototoi",a:"kemarin lusa",n:"Kanji: 一昨日."},
{k:"このあいだ",r:"konoaida",a:"tempo hari",n:"Waktu tidak spesifik di masa lalu."},
{k:"らいしゅう",r:"raishuu",a:"minggu depan",n:"Kanji: 来週."},
{k:"せんしゅう",r:"senshuu",a:"minggu lalu",n:"Kanji: 先週."},
{k:"けさ",r:"kesa",a:"tadi pagi",n:"Kanji: 今朝. Gabungan 今 (ini) + 朝 (pagi)."}
]},
"Keterangan Bulan & Tahun":{rows:[
{k:"せんせんげつ",r:"sensengetsu",a:"2 bulan lalu",n:"Kanji: 先々月. Sen + Sen + Gatsu. Dua bulan sebelum bulan ini."},
{k:"せんげつ",r:"sengetsu",a:"bulan lalu",n:"Kanji: 先月. Sen (sebelum/terdahulu) + Gatsu (bulan)."},
{k:"こんげつ",r:"kongetsu",a:"bulan ini",n:"Kanji: 今月. Kon (sekarang/ini) + Gatsu (bulan)."},
{k:"らいげつ",r:"raigetsu",a:"bulan depan",n:"Kanji: 来月. Rai (akan datang) + Gatsu (bulan)."},
{k:"さらいげつ",r:"saraigetsu",a:"2 bulan lagi",n:"Kanji: 再来月. Sa + Rai + Gatsu. Dua bulan dari sekarang."},
{k:"こんしゅう",r:"konshuu",a:"minggu ini",n:"Kanji: 今週. Kon (sekarang/ini) + Shuu (minggu). Pasangannya: senshuu (minggu lalu) dan raishuu (minggu depan) — sudah ada di Keterangan Hari."},
{k:"まいつき",r:"maitsuki",a:"setiap bulan",n:"Kanji: 毎月. Mai (setiap) + Tsuki (bulan). Dipakai untuk sesuatu yang berulang tiap bulan."},
{k:"おととし",r:"ototoshi",a:"2 tahun lalu",n:"Kanji: 一昨年. Dua tahun yang telah berlalu."},
{k:"きょねん",r:"kyonen",a:"tahun lalu",n:"Kanji: 去年. Kyo (pergi/lalu) + Nen (tahun)."},
{k:"ことし",r:"kotoshi",a:"tahun ini",n:"Kanji: 今年. Ko (sekarang) + Toshi (tahun)."},
{k:"らいねん",r:"rainen",a:"tahun depan",n:"Kanji: 来年. Rai (akan datang) + Nen (tahun)."},
{k:"さらいねん",r:"sarainen",a:"2 tahun lagi",n:"Kanji: 再来年. Dua tahun ke depan."},
{k:"ごねんご",r:"go nen go",a:"5 tahun lagi",n:"Kanji: 5年後. Go (5) + Nen (tahun) + Go (setelah/kemudian). Pola X年後 bisa dipakai untuk jarak tahun apapun."},
{k:"まいとし",r:"maitoshi",a:"setiap tahun",n:"Kanji: 毎年. Mai (setiap) + Toshi (tahun). Juga bisa dibaca 'maitoshi' atau 'mainen'."}
]},
"Jam":{rows:[
{k:"いちじ",r:"ichiji",a:"jam 1",n:"いち (1) + じ (jam). Penulisan waktu: angka + じ."},
{k:"にじ",r:"niji",a:"jam 2",n:"に (2) + じ (jam)."},
{k:"さんじ",r:"sanji",a:"jam 3",n:"さん (3) + じ."},
{k:"よじ",r:"yoji",a:"jam 4",n:"よん bukan し — pakai よ karena menghindari し (mati)."},
{k:"ごじ",r:"goji",a:"jam 5",n:"ご (5) + じ."},
{k:"ろくじ",r:"rokuji",a:"jam 6",n:"ろく (6) + じ."},
{k:"しちじ",r:"shichiji",a:"jam 7",n:"しち (7) + じ. Pakai しち, bukan なな, untuk menyebut jam."},
{k:"はちじ",r:"hachiji",a:"jam 8",n:"はち (8) + じ."},
{k:"くじ",r:"kuji",a:"jam 9",n:"く (9) + じ. Pakai く, bukan きゅう, untuk menyebut jam."},
{k:"じゅうじ",r:"juuji",a:"jam 10",n:"じゅう (10) + じ."},
{k:"じゅういちじ",r:"juuichiji",a:"jam 11",n:"じゅういち (11) + じ."},
{k:"じゅうにじ",r:"juuniji",a:"jam 12",n:"じゅうに (12) + じ."},
{k:"なんじ",r:"nanji",a:"jam berapa?",n:"なん (berapa) + じ (jam). Dipakai untuk menanyakan waktu."},
{k:"いちじはん",r:"ichiji han",a:"jam 1 setengah",n:"Contoh penggunaan はん (setengah) setelah jam."},
{k:"ごぜんろくじ",r:"gozen rokuji",a:"jam 6 pagi",n:"ごぜん (AM) + ろくじ (jam 6). ごぜん selalu di depan."},
{k:"ごごさんじ",r:"gogo sanji",a:"jam 3 sore",n:"ごご (PM) + さんじ (jam 3)."}
]},
"Menit":{rows:[
{k:"いっぷん",r:"ippun",a:"1 menit",n:"いち + ふん → いっぷん. Berubah karena aturan fonologi (rendaku)."},
{k:"にふん",r:"nifun",a:"2 menit",n:"に (2) + ふん. Tidak berubah."},
{k:"さんぷん",r:"sanpun",a:"3 menit",n:"さん + ふん → さんぷん. Berubah menjadi ぷん."},
{k:"よんふん",r:"yonfun",a:"4 menit",n:"よん (4) + ふん. Tidak berubah."},
{k:"ごふん",r:"gofun",a:"5 menit",n:"ご (5) + ふん. Tidak berubah."},
{k:"ろっぷん",r:"roppun",a:"6 menit",n:"ろく + ふん → ろっぷん. Konsonan ganda + ぷ."},
{k:"ななふん",r:"nanafun",a:"7 menit",n:"なな (7) + ふん. Tidak berubah."},
{k:"はっぷん",r:"happun",a:"8 menit",n:"はち + ふん → はっぷん. Konsonan ganda + ぷ."},
{k:"きゅうふん",r:"kyuufun",a:"9 menit",n:"きゅう (9) + ふん. Tidak berubah."},
{k:"じゅっぷん",r:"juppun",a:"10 menit",n:"じゅう + ふん → じゅっぷん. Konsonan ganda + ぷ."},
{k:"じゅうごふん",r:"juugofun",a:"15 menit",n:"じゅうご (15) + ふん."},
{k:"にじゅっぷん",r:"nijuppun",a:"20 menit",n:"にじゅう (20) + ふん → にじゅっぷん."},
{k:"さんじゅっぷん",r:"sanjuppun",a:"30 menit",n:"さんじゅう (30) + ふん → さんじゅっぷん. Sama dengan はん (setengah)."},
{k:"よんじゅっぷん",r:"yonjuppun",a:"40 menit",n:"よんじゅう (40) + ふん."},
{k:"ごじゅっぷん",r:"gojuppun",a:"50 menit",n:"ごじゅう (50) + ふん."},
{k:"なんぷん",r:"nanpun",a:"berapa menit?",n:"なん (berapa) + ふん → なんぷん. Untuk menanyakan menit."}
]},
"Bulan (Nama)":{rows:[
{k:"いちがつ",r:"ichigatsu",a:"Januari",n:"いち (1) + がつ (bulan). Semua bulan mengikuti pola: angka + がつ."},
{k:"にがつ",r:"nigatsu",a:"Februari",n:"に (2) + がつ."},
{k:"さんがつ",r:"sangatsu",a:"Maret",n:"さん (3) + がつ."},
{k:"しがつ",r:"shigatsu",a:"April",n:"し (4) + がつ. Di sini pakai し (bukan よん) untuk bulan."},
{k:"ごがつ",r:"gogatsu",a:"Mei",n:"ご (5) + がつ."},
{k:"ろくがつ",r:"rokugatsu",a:"Juni",n:"ろく (6) + がつ."},
{k:"しちがつ",r:"shichigatsu",a:"Juli",n:"しち (7) + がつ. Pakai しち untuk bulan."},
{k:"はちがつ",r:"hachigatsu",a:"Agustus",n:"はち (8) + がつ."},
{k:"くがつ",r:"kugatsu",a:"September",n:"く (9) + がつ. Pakai く untuk bulan."},
{k:"じゅうがつ",r:"juugatsu",a:"Oktober",n:"じゅう (10) + がつ."},
{k:"じゅういちがつ",r:"juuichigatsu",a:"November",n:"じゅういち (11) + がつ."},
{k:"じゅうにがつ",r:"juunigatsu",a:"Desember",n:"じゅうに (12) + がつ."},
{k:"なんがつ",r:"nangatsu",a:"bulan berapa?",n:"なん (berapa) + がつ. Untuk menanyakan bulan."}
]},
"Tanggal":{rows:[
{k:"ついたち",r:"tsuitachi",a:"tanggal 1",n:"Pengucapan khusus! Bukan 'ichiにち'. Berasal dari kata kuno untuk 'bulan penuh'."},
{k:"ふつか",r:"futsuka",a:"tanggal 2",n:"Pengucapan khusus. Tanggal 1-10 semuanya tidak beraturan, harus dihafal."},
{k:"みっか",r:"mikka",a:"tanggal 3",n:"Pengucapan khusus."},
{k:"よっか",r:"yokka",a:"tanggal 4",n:"Pengucapan khusus."},
{k:"いつか",r:"itsuka",a:"tanggal 5",n:"Pengucapan khusus. Juga bisa berarti 'suatu hari nanti' dalam konteks berbeda."},
{k:"むいか",r:"muika",a:"tanggal 6",n:"Pengucapan khusus."},
{k:"なのか",r:"nanoka",a:"tanggal 7",n:"Pengucapan khusus."},
{k:"ようか",r:"youka",a:"tanggal 8",n:"Pengucapan khusus."},
{k:"ここのか",r:"kokonoka",a:"tanggal 9",n:"Pengucapan khusus."},
{k:"とおか",r:"tooka",a:"tanggal 10",n:"Pengucapan khusus. Setelah tanggal 10, menjadi lebih teratur: angka + にち."},
{k:"じゅういちにち",r:"juuichinichi",a:"tanggal 11",n:"じゅういち (11) + にち. Mulai dari 11, pola angka + にち."},
{k:"じゅうにち",r:"juunichi",a:"tanggal 12",n:"じゅうに (12) + にち."},
{k:"じゅうさんにち",r:"juusannichi",a:"tanggal 13",n:"じゅうさん (13) + にち."},
{k:"じゅうよっか",r:"juuyokka",a:"tanggal 14",n:"Pengecualian! Pakai よっか (bukan じゅうよんにち)."},
{k:"じゅうごにち",r:"juugonichi",a:"tanggal 15",n:"じゅうご (15) + にち."},
{k:"はつか",r:"hatsuka",a:"tanggal 20",n:"Pengecualian! Pengucapan khusus, bukan にじゅうにち."},
{k:"にじゅうよっか",r:"nijuuyokka",a:"tanggal 24",n:"Pengecualian! Pakai よっか di akhir."},
{k:"にじゅうごにち",r:"nijuugonichi",a:"tanggal 25",n:"にじゅうご (25) + にち. Pola normal."},
{k:"さんじゅうにち",r:"sanjuunichi",a:"tanggal 30",n:"さんじゅう (30) + にち."},
{k:"さんじゅういちにち",r:"sanjuuichinichi",a:"tanggal 31",n:"Tanggal terakhir yang ada di kalender Jepang."},
{k:"なんにち",r:"nannichi",a:"tanggal berapa?",n:"なん (berapa) + にち. Untuk menanyakan tanggal."}
]},
"Bagian Tubuh":{rows:[
{k:"からだ",r:"karada",a:"tubuh",n:"Kanji: 体."},
{k:"かお",r:"kao",a:"wajah",n:"Kanji: 顔."},
{k:"あたま",r:"atama",a:"kepala",n:"Kanji: 頭."},
{k:"かみ / かみのけ",r:"kami / kami no ke",a:"rambut",n:"Kanji: 髪. Homofon dengan 'kami' = kertas (紙) dan dewa (神)!"},
{k:"め",r:"me",a:"mata",n:"Kanji: 目."},
{k:"はな",r:"hana (hidung)",a:"hidung",n:"Kanji: 鼻. Homofon dengan はな (花) = bunga!"},
{k:"みみ",r:"mimi",a:"telinga",n:"Kanji: 耳."},
{k:"くち",r:"kuchi",a:"mulut",n:"Kanji: 口."},
{k:"は",r:"ha",a:"gigi",n:"Kanji: 歯."},
{k:"くび",r:"kubi",a:"leher",n:"Kanji: 首."},
{k:"かた",r:"kata",a:"bahu",n:"Kanji: 肩."},
{k:"むね",r:"mune",a:"dada",n:"Kanji: 胸."},
{k:"て",r:"te",a:"tangan",n:"Kanji: 手."},
{k:"ゆび",r:"yubi",a:"jari",n:"Kanji: 指."},
{k:"うで",r:"ude",a:"lengan",n:"Kanji: 腕."},
{k:"あし",r:"ashi",a:"kaki",n:"Kanji: 足."},
{k:"ひざ",r:"hiza",a:"lutut",n:"Kanji: 膝."},
{k:"はだ",r:"hada",a:"kulit",n:"Kanji: 肌."}
]},
"Warna":{rows:[
{k:"あか",r:"aka",a:"merah",n:"Kanji: 赤. Warna paling kuat dalam budaya Jepang."},
{k:"あお",r:"ao",a:"biru / hijau (tua)",n:"Kanji: 青. Secara historis mencakup biru DAN hijau."},
{k:"きいろ",r:"kiiro",a:"kuning",n:"Kanji: 黄色. Ki (kuning) + Iro (warna)."},
{k:"みどり",r:"midori",a:"hijau",n:"Kanji: 緑. Hijau yang lebih cerah/segar dari 'ao'."},
{k:"くろ",r:"kuro",a:"hitam",n:"Kanji: 黒."},
{k:"しろ",r:"shiro",a:"putih",n:"Kanji: 白."},
{k:"ちゃいろ",r:"chairo",a:"coklat",n:"Kanji: 茶色. Cha (teh) + Iro (warna). 'Warna teh'."},
{k:"はいいろ",r:"haiiro",a:"abu-abu",n:"Kanji: 灰色. Hai (abu) + Iro (warna)."},
{k:"むらさき",r:"murasaki",a:"ungu",n:"Kanji: 紫. Warna bangsawan di Jepang kuno."},
{k:"オレンジ",r:"orenji",a:"oranye",n:"Serapan 'orange'."},
{k:"ピンク",r:"pinku",a:"merah muda / pink",n:"Serapan 'pink'. Identik dengan bunga sakura."},
{k:"きんいろ",r:"kiniro",a:"emas",n:"Kanji: 金色. Kin (emas) + Iro (warna)."},
{k:"ぎんいろ",r:"giniro",a:"perak",n:"Kanji: 銀色. Gin (perak) + Iro (warna)."}
]},
"Rasa":{rows:[
{k:"あまい",r:"amai",a:"manis",n:"Kanji: 甘い."},
{k:"しょっぱい",r:"shoppai",a:"asin (terlalu asin)",n:"Dari 'shio' (garam)."},
{k:"にがい",r:"nigai",a:"pahit",n:"Kanji: 苦い."},
{k:"すっぱい",r:"suppai",a:"asam",n:"Kanji: 酸っぱい."},
{k:"からい",r:"karai",a:"pedas / gurih-asin",n:"Kanji: 辛い."},
{k:"おいしい",r:"oishii",a:"enak / lezat (sopan)",n:"Kanji: 美味しい."},
{k:"まずい",r:"mazui",a:"tidak enak",n:"Kanji: 不味い. Lawan kata dari 'oishii'."},
{k:"うまみ",r:"umami",a:"gurih (rasa ke-5)",n:"Rasa kelima — kini diakui secara ilmiah internasional."}
]},
"Kata Tanya":{rows:[
{k:"なに / なん",r:"nani / nan",a:"apa",n:"Kanji: 何."},
{k:"だれ",r:"dare",a:"siapa",n:"Kanji: 誰. Bentuk sopan: donata."},
{k:"どこ",r:"doko",a:"di mana",n:"Kanji: 何処."},
{k:"いつ",r:"itsu",a:"kapan",n:"Kanji: 何時."},
{k:"なぜ / どうして",r:"naze / doushite",a:"mengapa",n:"'Naze' lebih formal. 'Doushite' lebih umum di percakapan."},
{k:"どう",r:"dou",a:"bagaimana",n:"Kanji: 如何. 'Dou desu ka?' = bagaimana?"},
{k:"いくつ",r:"ikutsu",a:"berapa (jumlah / usia)",n:"Kanji: 幾つ."},
{k:"いくら",r:"ikura",a:"berapa harganya",n:"Kanji: 幾ら. 'Ikura desu ka?' = berapa harganya?"},
{k:"どれ",r:"dore",a:"yang mana (dari banyak)",n:"Kanji: 何れ. Pilihan dari 3 atau lebih."},
{k:"どちら",r:"dochira",a:"yang mana (dari dua)",n:"Kanji: 何方. Pilihan dari 2 opsi."},
{k:"どんな",r:"donna",a:"seperti apa / jenis apa",n:"Kanji: どんな. Menanyakan jenis atau sifat sesuatu."},
{k:"なんで",r:"nande",a:"kenapa (santai)",n:"Kanji: 何で. Versi santai dari naze/doushite."}
]},
"Kata Penunjuk (Ko-So-A-Do)":{rows:[
{k:"これ",r:"kore",a:"ini (dekat pembicara)",n:"Pola KO-SO-A-DO: ko=dekat aku, so=dekat kamu, a=jauh, do=tanya."},
{k:"それ",r:"sore",a:"itu (dekat pendengar)",n:"Benda dekat pendengar."},
{k:"あれ",r:"are",a:"itu (jauh dari keduanya)",n:"Benda jauh dari pembicara maupun pendengar."},
{k:"どれ",r:"dore",a:"yang mana?",n:"Bentuk tanya dari seri ini."},
{k:"この",r:"kono",a:"ini ~ (menerangkan benda)",n:"Dipakai sebelum kata benda."},
{k:"その",r:"sono",a:"itu ~ (dekat pendengar)",n:"Menerangkan benda dekat pendengar."},
{k:"あの",r:"ano",a:"itu ~ (jauh)",n:"Menerangkan benda jauh."},
{k:"どの",r:"dono",a:"yang mana ~ ?",n:"Bentuk tanya."},
{k:"ここ",r:"koko",a:"di sini (dekat pembicara)",n:"Tempat dekat pembicara."},
{k:"そこ",r:"soko",a:"di situ (dekat pendengar)",n:"Tempat dekat pendengar."},
{k:"あそこ",r:"asoko",a:"di sana (jauh)",n:"Tempat jauh dari keduanya."},
{k:"どこ",r:"doko",a:"di mana?",n:"Bentuk tanya untuk tempat."},
{k:"こちら",r:"kochira",a:"ke sini / ini (sopan)",n:"Versi sopan dari koko/kore."},
{k:"そちら",r:"sochira",a:"ke situ / itu (sopan)",n:"Versi sopan dari soko/sore."},
{k:"あちら",r:"achira",a:"ke sana / itu (sopan)",n:"Versi sopan dari asoko/are."}
]},
"Kata Keterangan Umum":{rows:[
{k:"とても",r:"totemo",a:"sangat / sekali",n:"Kata penguat paling umum."},
{k:"すごく",r:"sugoku",a:"sangat (santai)",n:"Lebih santai dari totemo."},
{k:"あまり",r:"amari",a:"tidak terlalu ~ (dengan negatif)",n:"Selalu dipakai dengan kalimat negatif."},
{k:"ぜんぜん",r:"zenzen",a:"sama sekali tidak (dengan negatif)",n:"Selalu dengan negatif dalam bahasa formal."},
{k:"もっと",r:"motto",a:"lebih (lagi)",n:"'Motto yukkuri' = lebih pelan lagi."},
{k:"もう",r:"mou",a:"sudah / lagi",n:"Dua arti: (1) sudah, (2) lagi."},
{k:"まだ",r:"mada",a:"masih / belum",n:"'Mada desu' = belum."},
{k:"すぐ",r:"sugu",a:"segera / langsung",n:"'Sugu kimasu' = segera datang."},
{k:"たくさん",r:"takusan",a:"banyak",n:"Untuk orang, benda, atau jumlah abstrak."},
{k:"すこし",r:"sukoshi",a:"sedikit",n:"'Sukoshi matte kudasai' = tolong tunggu sebentar."},
{k:"たぶん",r:"tabun",a:"mungkin / sepertinya",n:"Kemungkinan ~70-80%."},
{k:"もちろん",r:"mochiron",a:"tentu saja / sudah pasti",n:"Keyakinan 100%."},
{k:"ほんとうに",r:"hontouni",a:"sungguh / benar-benar",n:"'Hontou ni?' = Sungguh?"}
]},
"Kegiatan Rutin":{rows:[
{k:"おきます",r:"okimasu",a:"bangun tidur",n:"Dari 'okiru'. Lawan dari 'nemasu'."},
{k:"ねます",r:"nemasu",a:"tidur",n:"Dari 'neru'."},
{k:"あらいます",r:"araimasu",a:"mencuci / membasuh",n:"'Te wo araimasu' = mencuci tangan."},
{k:"みがきます",r:"migakimasu",a:"menggosok / menyikat",n:"'Ha wo migakimasu' = menggosok gigi."},
{k:"きがえます",r:"kigaemasu",a:"ganti baju",n:"Ki (memakai pakaian) + Kaeru (mengganti)."},
{k:"あるきます",r:"arukimasu",a:"berjalan kaki",n:"Dari 'aruku'."},
{k:"はしります",r:"hashirimasu",a:"berlari",n:"Dari 'hashiru'."},
{k:"べんきょうします",r:"benkyou shimasu",a:"belajar",n:"'Nihongo wo benkyou shimasu' = belajar bahasa Jepang."},
{k:"はたらきます",r:"hatarakimasu",a:"bekerja",n:"Dari 'hataraku'."},
{k:"やすみます",r:"yasumimasu",a:"beristirahat / absen",n:"'Kyou wa yasumimasu' = hari ini tidak masuk."},
{k:"でかけます",r:"dekakemasu",a:"keluar / pergi keluar",n:"'Chotto dekakemasu' = sebentar pergi keluar."},
{k:"かいものをします",r:"kaimono wo shimasu",a:"belanja",n:"Kai (membeli) + Mono (barang) + shimasu."},
{k:"りょうりをします",r:"ryouri wo shimasu",a:"memasak",n:"Ryouri (masakan) + shimasu."},
{k:"そうじをします",r:"souji wo shimasu",a:"bersih-bersih",n:"Di sekolah Jepang, souji adalah piket harian."},
{k:"せんたくをします",r:"sentaku wo shimasu",a:"mencuci pakaian",n:"Sentaku (laundry) + shimasu."}
]},
"Profesi & Pekerjaan":{rows:[
{k:"いしゃ",r:"isha",a:"dokter",n:"Kanji: 医者. Disapa 'sensei'."},
{k:"かんごし",r:"kangoshi",a:"perawat",n:"Kanji: 看護師."},
{k:"きょうし / せんせい",r:"kyoushi / sensei",a:"guru / pengajar",n:"Kyoushi lebih formal; sensei untuk menyapa."},
{k:"がくせい",r:"gakusei",a:"siswa / mahasiswa",n:"Kanji: 学生."},
{k:"かいしゃいん",r:"kaishain",a:"karyawan perusahaan",n:"Kanji: 会社員."},
{k:"こうむいん",r:"koumuin",a:"pegawai negeri",n:"Kanji: 公務員."},
{k:"エンジニア",r:"enjinia",a:"insinyur / engineer",n:"Serapan 'engineer'."},
{k:"けいさつかん",r:"keisatsukan",a:"polisi (petugas)",n:"Kanji: 警察官."},
{k:"りょうりにん / コック",r:"ryourinin / kokku",a:"juru masak / chef",n:"Kanji: 料理人."},
{k:"のうか",r:"nouka",a:"petani",n:"Kanji: 農家."},
{k:"かしゅ",r:"kashu",a:"penyanyi",n:"Kanji: 歌手."},
{k:"べんごし",r:"bengoshi",a:"pengacara",n:"Kanji: 弁護士."}
]},
"Arah & Posisi":{rows:[
{k:"みぎ",r:"migi",a:"kanan",n:"Kanji: 右."},
{k:"ひだり",r:"hidari",a:"kiri",n:"Kanji: 左."},
{k:"まっすぐ",r:"massugu",a:"lurus",n:"'Massugu itte kudasai' = tolong jalan lurus."},
{k:"まえ",r:"mae",a:"depan / sebelum",n:"Kanji: 前."},
{k:"うしろ",r:"ushiro",a:"belakang",n:"Kanji: 後ろ."},
{k:"うえ",r:"ue",a:"atas / di atas",n:"Kanji: 上."},
{k:"した",r:"shita",a:"bawah / di bawah",n:"Kanji: 下."},
{k:"なか",r:"naka",a:"dalam / di dalam",n:"Kanji: 中."},
{k:"そと",r:"soto",a:"luar / di luar",n:"Kanji: 外."},
{k:"となり",r:"tonari",a:"sebelah / di sebelah",n:"Kanji: 隣."},
{k:"ちかく",r:"chikaku",a:"dekat / di dekat",n:"Kanji: 近く."},
{k:"ひがし",r:"higashi",a:"timur",n:"Kanji: 東."},
{k:"にし",r:"nishi",a:"barat",n:"Kanji: 西."},
{k:"みなみ",r:"minami",a:"selatan",n:"Kanji: 南."},
{k:"きた",r:"kita",a:"utara",n:"Kanji: 北."}
]},
"Ekspresi di Kelas":{rows:[
{k:"わかりました",r:"wakarimashita",a:"saya mengerti",n:"Bentuk lampau sopan dari 'wakaru'."},
{k:"わかりません",r:"wakarimasen",a:"saya tidak mengerti",n:"Bentuk negatif sopan."},
{k:"もういちどおねがいします",r:"mou ichido onegaishimasu",a:"tolong ulangi sekali lagi",n:"Mou (lagi) + ichido (sekali) + onegaishimasu (tolong)."},
{k:"ゆっくりはなしてください",r:"yukkuri hanashite kudasai",a:"tolong bicara lebih pelan",n:"Yukkuri (pelan-pelan) + hanashite + kudasai."},
{k:"しつもんがあります",r:"shitsumon ga arimasu",a:"saya punya pertanyaan",n:"Shitsumon (pertanyaan) + ga + arimasu (ada)."},
{k:"おしえてください",r:"oshiete kudasai",a:"tolong ajari saya",n:"Oshiete (mengajari) + kudasai (tolong)."},
{k:"トイレにいってもいいですか",r:"toire ni itte mo ii desu ka",a:"boleh saya ke toilet?",n:"Cara sopan meminta izin ke kamar kecil di kelas."},
{k:"きょうのしゅくだいはなんですか",r:"kyou no shukudai wa nan desu ka",a:"apa PR hari ini?",n:"Shukudai (宿題) = PR/pekerjaan rumah."},
{k:"テストはいつですか",r:"tesuto wa itsu desu ka",a:"ujian kapan?",n:"Tesuto (serapan 'test') + wa itsu desu ka (kapan?)."},
{k:"ちょっとまってください",r:"chotto matte kudasai",a:"tolong tunggu sebentar",n:"Chotto (sedikit/sebentar) + matte + kudasai."}
]},
"Counter (Kata Bilangan)":{rows:[
{k:"〜ひき",r:"~hiki",a:"ekor (hewan kecil)",n:"Untuk kucing, anjing, ikan. 1=ippiki, 2=nihiki, 3=sanbiki."},
{k:"〜とう",r:"~tou",a:"ekor (hewan besar)",n:"Untuk sapi, gajah, kuda. 1=ittou, 2=nitou."},
{k:"〜わ",r:"~wa",a:"ekor (burung)",n:"Khusus untuk burung. 1=ichiwa, 2=niwa."},
{k:"〜まい",r:"~mai",a:"lembar (benda tipis datar)",n:"Untuk kertas, piring, baju, foto. 1=ichimai."},
{k:"〜ほん",r:"~hon",a:"batang (benda panjang)",n:"Untuk pensil, botol, pohon. 1=ippon, 2=nihon, 3=sanbon."},
{k:"〜さつ",r:"~satsu",a:"buah (buku / majalah)",n:"Khusus untuk buku dan majalah. 1=issatsu."},
{k:"〜だい",r:"~dai",a:"buah (mesin / kendaraan)",n:"Untuk kendaraan, peralatan. 1=ichidai."},
{k:"〜こ",r:"~ko",a:"buah (benda kecil bulat)",n:"Untuk apel, telur, batu. 1=ikko."},
{k:"〜はい",r:"~hai",a:"cangkir / gelas (cairan)",n:"Untuk cairan dalam wadah. 1=ippai."},
{k:"〜にん",r:"~nin",a:"orang",n:"1=hitori, 2=futari, 3=sannin."},
{k:"〜かい",r:"~kai",a:"kali / lantai",n:"(1) berapa kali (回), (2) lantai gedung (階). 1=ikkai."},
{k:"〜えん",r:"~en",a:"yen (mata uang)",n:"Counter untuk uang Jepang."}
]},

"Peralatan Masak":{rows:[
{k:"なべ",r:"nabe",a:"panci",n:"Kata asli Jepang kuno (鍋). Juga nama hidangan hot pot populer."},
{k:"フライパン",r:"furaipan",a:"wajan datar",n:"Fry + Pan."},
{k:"やかん",r:"yakan",a:"ketel air",n:"Dulu untuk merebus jamu, kini untuk air minum."},
{k:"オーブン",r:"oobun",a:"oven",n:"Serapan 'oven'."},
{k:"でんしレンジ",r:"denshi renji",a:"microwave",n:"'Denshi' (elektronik) + 'renji' (dari 'range')."},
{k:"トースター",r:"toosutaa",a:"pemanggang roti",n:"Serapan 'toaster'."},
{k:"ミキサー",r:"mikisaa",a:"blender",n:"Dari 'mixer'. Di Jepang maknanya bergeser jadi blender."},
{k:"すいはんき",r:"suihanki",a:"rice cooker",n:"Kanji: 炊飯器. 'Mesin penanak nasi'."},
{k:"コンロ",r:"konro",a:"kompor",n:"Kata asli Jepang (焜炉). 'Tungku api'."}
]},
"Alat Dapur":{rows:[
{k:"ほうちょう",r:"houchou",a:"pisau dapur",n:"Kanji: 包丁. Dari nama koki legendaris Cina kuno."},
{k:"まないた",r:"manaita",a:"talenan",n:"Kanji: まな板. 'Papan untuk memotong ikan'."},
{k:"キッチンばさみ",r:"kitchin basami",a:"gunting dapur",n:"Kitchin (dapur) + Hasami (gunting)."},
{k:"おたま",r:"otama",a:"sendok sayur",n:"Singkatan dari Otamajakushi (kecebong). Bentuknya mirip kecebong."},
{k:"へら",r:"hera",a:"spatula",n:"Kanji: 箆. Bilah tipis/sudip datar."},
{k:"トング",r:"tongu",a:"penjepit",n:"Serapan 'tongs'."},
{k:"しゃもじ",r:"shamoji",a:"sendok nasi",n:"Kanji: 杓文字."},
{k:"スプーン",r:"supuun",a:"sendok",n:"Serapan 'spoon'."},
{k:"フォーク",r:"fooku",a:"garpu",n:"Serapan 'fork'."},
{k:"はし",r:"hashi",a:"sumpit",n:"Kanji: 箸. 'Jembatan' antara makanan dan mulut."},
{k:"ざる",r:"zaru",a:"saringan bambu",n:"Keranjang anyaman bambu berlubang."},
{k:"おろしがね",r:"oroshigane",a:"parutan",n:"Kanji: おろし金. Untuk memarut jahe, lobak, dsb."}
]},
"Wadah & Perabot":{rows:[
{k:"ボウル",r:"booru",a:"mangkuk besar",n:"Serapan 'bowl'."},
{k:"さら",r:"sara",a:"piring",n:"Kanji: 皿."},
{k:"ちゃわん",r:"chawan",a:"mangkuk nasi",n:"Kanji: 茶碗. Aslinya 'mangkuk teh', kini khusus mangkuk nasi."},
{k:"コップ",r:"koppu",a:"gelas",n:"Dari bahasa Belanda/Portugis. Gelas tanpa gagang."},
{k:"カップ",r:"kappu",a:"cangkir",n:"Serapan 'cup'."},
{k:"マグカップ",r:"magu kappu",a:"mug",n:"Mug + Cup. Cangkir mug besar bergagang."},
{k:"れいぞうこ",r:"reizouko",a:"kulkas",n:"Kanji: 冷蔵庫. 'Kotak penyimpanan dingin'."},
{k:"れいとうこ",r:"reitouko",a:"freezer",n:"Kanji: 冷凍庫. 'Kotak pembeku'."},
{k:"ゴミばこ",r:"gomibako",a:"tempat sampah",n:"Kanji: ゴミ箱. 'Kotak sampah'."},
{k:"たな",r:"tana",a:"rak",n:"Kanji: 棚."},
{k:"ひきだし",r:"hikidashi",a:"laci",n:"Kanji: 引き出し. 'Kotak yang ditarik keluar'."}
]},
"Bumbu & Bahan":{rows:[
{k:"しお",r:"shio",a:"garam",n:"Kata asli Jepang kuno (塩)."},
{k:"さとう",r:"satou",a:"gula",n:"Kanji: 砂糖. 'Gula pasir'."},
{k:"こしょう",r:"koshou",a:"merica / lada",n:"Kanji: 胡椒."},
{k:"しょうゆ",r:"shouyu",a:"kecap asin",n:"Kanji: 醤油. Bumbu paling khas masakan Jepang."},
{k:"みそ",r:"miso",a:"pasta miso",n:"Kanji: 味噌. Pasta dari fermentasi kedelai."},
{k:"す",r:"su",a:"cuka",n:"Kanji: 酢."},
{k:"あぶら",r:"abura",a:"minyak",n:"Kanji: 油."},
{k:"こめ",r:"kome",a:"beras (mentah)",n:"Kanji: 米. Khusus beras belum dimasak."},
{k:"にく",r:"niku",a:"daging",n:"Kanji: 肉."},
{k:"やさい",r:"yasai",a:"sayuran",n:"Kanji: 野菜. 'Sayuran yang tumbuh di ladang'."},
{k:"くだもの",r:"kudamono",a:"buah-buahan",n:"Kanji: 果物. 'Benda hasil pohon'."},
{k:"パン",r:"pan",a:"roti",n:"Serapan dari bahasa Portugis 'Pão'."},
{k:"ごはん",r:"gohan",a:"nasi (matang)",n:"Kanji: 御飯. Beda dengan こめ (kome) yang masih mentah."}
]},
"Bahan Pelengkap":{rows:[
{k:"ラップ",r:"rappu",a:"plastik wrap",n:"Serapan 'wrap'. Plastik pembungkus makanan."},
{k:"アルミホイル",r:"arumi hoiru",a:"aluminium foil",n:"Serapan 'aluminum foil'."},
{k:"キッチンペーパー",r:"kitchin peepaa",a:"tisu dapur",n:"Serapan 'kitchen paper'."},
{k:"スポンジ",r:"suponji",a:"spons",n:"Serapan 'sponge'. Untuk mencuci piring."},
{k:"せんざい",r:"senzai",a:"sabun cuci / deterjen",n:"Kanji: 洗剤. 'Bahan kimia pembersih'."}
]},
"Sapaan & Ekspresi":{rows:[
{k:"おはようございます",r:"ohayou gozaimasu",a:"selamat pagi (formal)",n:"Bentuk santai: 'ohayou'. Berlaku sampai ~10-11 pagi."},
{k:"こんにちは",r:"konnichiwa",a:"halo / selamat siang",n:"~10 pagi hingga ~6 sore. は dibaca 'wa'."},
{k:"こんばんは",r:"konbanwa",a:"selamat malam",n:"~6 sore ke atas. は dibaca 'wa'."},
{k:"おつかれさまです",r:"otsukaresama desu",a:"salam di tengah / akhir hari",n:"Salam kedua dan seterusnya, bukan salam pertama."},
{k:"よろしくおねがいします",r:"yoroshiku onegaishimasu",a:"mohon bantuannya",n:"Serbaguna: saat kenalan baru, meminta tolong, menitipkan sesuatu."},
{k:"しつれいします",r:"shitsureishimasu",a:"permisi",n:"Saat masuk ruangan, melewati orang, memulai gangguan."},
{k:"はじめまして",r:"hajimemashite",a:"senang berkenalan",n:"Selalu diikuti yoroshiku onegaishimasu."},
{k:"ありがとうございます",r:"arigatou gozaimasu",a:"terima kasih (formal)",n:"Bentuk santai: 'arigatou'."},
{k:"すみません",r:"sumimasen",a:"permisi / maaf (ringan)",n:"Serbaguna: memanggil pelayan, minta maaf ringan, permisi."},
{k:"ごめんなさい",r:"gomennasai",a:"maaf (tulus / informal)",n:"Lebih tulus dan personal dari sumimasen."},
{k:"いってきます",r:"ittekimasu",a:"saya pergi dulu",n:"'Saya pergi dan akan kembali'. Pasangan: 'itterasshai'."},
{k:"ただいま",r:"tadaima",a:"saya sudah pulang",n:"'Baru saja sekarang'. Pasangan: 'okaerinasai'."},
{k:"いただきます",r:"itadakimasu",a:"selamat makan (sebelum makan)",n:"Sangat penting dalam budaya makan Jepang."},
{k:"ごちそうさまでした",r:"gochisousama deshita",a:"terima kasih atas makanannya",n:"Diucapkan setelah selesai makan."},
{k:"さようなら",r:"sayounara",a:"selamat tinggal (formal)",n:"Perpisahan formal yang cukup final."},
{k:"じゃあね",r:"jaa ne",a:"dadah / sampai jumpa (santai)",n:"Paling santai. Hanya untuk teman dekat."},
{k:"またね",r:"mata ne",a:"sampai ketemu lagi",n:"Lebih hangat dari 'jaa ne'."},
{k:"おやすみなさい",r:"oyasuminasai",a:"selamat tidur / selamat malam",n:"'Istirahatlah'. Bentuk santai: 'oyasumi'."}
]}
};

// ─── DATA: PARTIKEL ───
const PT=[
{sym:"は",r:"wa",name:"Topik (topic marker)",
desc:"Menandai topik kalimat. Ditulis 'ha' tapi dibaca 'wa'.",
ex:[
{jp:"わたし<b class='ph'>は</b>がくせいです。",id:"Saya adalah siswa."},
{jp:"これ<b class='ph'>は</b>ほんです。",id:"Ini adalah buku."},
{jp:"きょう<b class='ph'>は</b>さむいです。",id:"Hari ini dingin."}]},
{sym:"が",r:"ga",name:"Subjek (subject marker)",
desc:"Menandai subjek gramatikal. Dipakai saat subjek baru, menekankan siapa yang melakukan, atau kalimat eksistensial.",
ex:[
{jp:"ねこ<b class='ph'>が</b>います。",id:"Ada kucing."},
{jp:"だれ<b class='ph'>が</b>きましたか？",id:"Siapa yang datang?"},
{jp:"わたし<b class='ph'>が</b>やります。",id:"Saya (lah) yang akan melakukannya."}]},
{sym:"を",r:"wo/o",name:"Objek (object marker)",
desc:"Menandai objek langsung dari kata kerja transitif.",
ex:[
{jp:"ほん<b class='ph'>を</b>よみます。",id:"Membaca buku."},
{jp:"おちゃ<b class='ph'>を</b>のみます。",id:"Minum teh."},
{jp:"えき<b class='ph'>を</b>でます。",id:"Keluar dari stasiun."}]},
{sym:"に",r:"ni",name:"Tujuan / Lokasi / Waktu",
desc:"Serba guna: tujuan gerakan, lokasi keberadaan, titik waktu, atau penerima aksi.",
ex:[
{jp:"がっこう<b class='ph'>に</b>いきます。",id:"Pergi ke sekolah."},
{jp:"つくえのうえ<b class='ph'>に</b>あります。",id:"Ada di atas meja."},
{jp:"さんじ<b class='ph'>に</b>あいましょう。",id:"Mari bertemu jam 3."}]},
{sym:"で",r:"de",name:"Tempat Aksi / Cara / Alat",
desc:"Tempat suatu aksi berlangsung, alat/cara yang digunakan.",
ex:[
{jp:"こうえん<b class='ph'>で</b>あそびます。",id:"Bermain di taman."},
{jp:"でんしゃ<b class='ph'>で</b>いきます。",id:"Pergi dengan kereta."},
{jp:"にほんご<b class='ph'>で</b>はなします。",id:"Berbicara dalam bahasa Jepang."}]},
{sym:"へ",r:"e",name:"Arah (direction marker)",
desc:"Menunjukkan arah gerakan. Ditulis 'he' tapi dibaca 'e'.",
ex:[
{jp:"とうきょう<b class='ph'>へ</b>いきます。",id:"Pergi menuju Tokyo."},
{jp:"うち<b class='ph'>へ</b>かえります。",id:"Pulang ke rumah."},
{jp:"みぎ<b class='ph'>へ</b>まがります。",id:"Belok ke kanan."}]},
{sym:"の",r:"no",name:"Kepemilikan / Penghubung",
desc:"Seperti apostrophe-s (') dalam bahasa Inggris. Menghubungkan dua kata benda.",
ex:[
{jp:"わたし<b class='ph'>の</b>ほん",id:"buku saya"},
{jp:"にほん<b class='ph'>の</b>たべもの",id:"makanan Jepang"},
{jp:"がっこう<b class='ph'>の</b>せんせい",id:"guru sekolah"}]},
{sym:"と",r:"to",name:"Dan / Bersama",
desc:"Menghubungkan dua kata benda (dan), atau menyatakan menemani (bersama).",
ex:[
{jp:"ねこ<b class='ph'>と</b>いぬ",id:"kucing dan anjing"},
{jp:"ともだち<b class='ph'>と</b>いきます。",id:"Pergi bersama teman."},
{jp:"おちゃ<b class='ph'>と</b>コーヒー",id:"teh dan kopi"}]},
{sym:"も",r:"mo",name:"Juga / Pun",
desc:"Berarti 'juga' atau 'pun'. Menggantikan partikel は, が, atau を.",
ex:[
{jp:"わたし<b class='ph'>も</b>がくせいです。",id:"Saya juga siswa."},
{jp:"これ<b class='ph'>も</b>いいです。",id:"Ini juga bagus."},
{jp:"なに<b class='ph'>も</b>たべません。",id:"Tidak makan apapun."}]},
{sym:"か",r:"ka",name:"Partikel Tanya",
desc:"Di akhir kalimat untuk mengubahnya menjadi pertanyaan.",
ex:[
{jp:"これはほんです<b class='ph'>か</b>？",id:"Apakah ini buku?"},
{jp:"いきます<b class='ph'>か</b>？",id:"Apakah akan pergi?"},
{jp:"なんじです<b class='ph'>か</b>？",id:"Jam berapa?"}]},
{sym:"ね",r:"ne",name:"Konfirmasi / Persetujuan",
desc:"Di akhir kalimat untuk meminta konfirmasi. Seperti 'kan?' atau 'ya?' dalam Bahasa Indonesia.",
ex:[
{jp:"いいてんきです<b class='ph'>ね</b>。",id:"Cuacanya bagus ya."},
{jp:"むずかしいです<b class='ph'>ね</b>。",id:"Susah ya."},
{jp:"そうです<b class='ph'>ね</b>。",id:"Begitu ya."}]},
{sym:"よ",r:"yo",name:"Penegasan / Informasi Baru",
desc:"Menyatakan informasi yang diyakini pembicara. Seperti 'lho' atau 'tahu tidak' dalam Bahasa Indonesia.",
ex:[
{jp:"これはおいしいです<b class='ph'>よ</b>。",id:"Ini enak lho."},
{jp:"もうじかんです<b class='ph'>よ</b>。",id:"Sudah waktunya lho."},
{jp:"だいじょうぶです<b class='ph'>よ</b>。",id:"Tidak apa-apa kok."}]},
{sym:"から",r:"kara",name:"Dari / Karena",
desc:"(1) titik awal dalam ruang atau waktu ('dari'), (2) alasan ('karena').",
ex:[
{jp:"にほん<b class='ph'>から</b>きました。",id:"Datang dari Jepang."},
{jp:"くじ<b class='ph'>から</b>はじまります。",id:"Mulai dari jam 9."},
{jp:"つかれた<b class='ph'>から</b>、ねます。",id:"Karena lelah, tidur."}]},
{sym:"まで",r:"made",name:"Sampai / Hingga",
desc:"Batas akhir dalam ruang atau waktu. Sering berpasangan dengan 'kara'.",
ex:[
{jp:"えき<b class='ph'>まで</b>あるきます。",id:"Berjalan kaki sampai stasiun."},
{jp:"くじ<b class='ph'>まで</b>はたらきます。",id:"Bekerja sampai jam 9."},
{jp:"ここ<b class='ph'>まで</b>でいいです。",id:"Sampai sini saja cukup."}]}
];

// ─── DATA: PARTIKEL LANJUTAN & POLA GRAMATIKAL ───
// Dipisah dari PT (partikel dasar) dan KT (kotoba)
// karena statusnya berbeda: ada yg murni partikel, ada konjungsi, ada pola tata bahasa.
const PT_ADV = {
  "Partikel (助詞)": [
    {sym:"だけ",r:"dake",kind:"Partikel (助詞 / joshi)",
    desc:"Membatasi pada satu hal saja. Tidak ada nuansa kekurangan seperti しか.",
    ex:[
      {jp:"これ<b class='ph'>だけ</b>ください。",id:"Tolong berikan ini saja."},
      {jp:"すこし<b class='ph'>だけ</b>たべた。",id:"Makan sedikit saja."},
      {jp:"かれ<b class='ph'>だけ</b>がしっている。",id:"Hanya dia yang tahu."}]},
    {sym:"しか",r:"shika",kind:"Partikel (係助詞 / kakarijoshi)",
    desc:"Hanya... (dengan nuansa kekurangan). Selalu diikuti bentuk negatif.",
    ex:[
      {jp:"ひゃくえん<b class='ph'>しか</b>ない。",id:"Cuma punya 100 yen (kurang)."},
      {jp:"かれ<b class='ph'>しか</b>こなかった。",id:"Yang datang hanya dia."},
      {jp:"これ<b class='ph'>しか</b>できない。",id:"Ini satu-satunya yang bisa kulakukan."}]},
    {sym:"でも",r:"demo",kind:"Partikel (係助詞)",
    desc:"Multi-fungsi: (1) tapi/namun di awal kalimat, (2) bahkan ~pun, (3) atau semacamnya.",
    ex:[
      {jp:"こども<b class='ph'>でも</b>わかる。",id:"Bahkan anak kecil pun mengerti."},
      {jp:"おちゃ<b class='ph'>でも</b>のみますか？",id:"Mau minum teh atau apa gitu?"},
      {jp:"<b class='ph'>でも</b>、むずかしいです。",id:"Tapi, itu sulit."}]},
    {sym:"とか",r:"toka",kind:"Partikel (並立助詞 / heiretsu joshi)",
    desc:"Menyebutkan contoh dari daftar tidak lengkap. Lebih santai dari や.",
    ex:[
      {jp:"ねこ<b class='ph'>とか</b>いぬ<b class='ph'>とか</b>がすきです。",id:"Suka kucing, anjing, dan lain-lain."},
      {jp:"えいが<b class='ph'>とか</b>みたい。",id:"Pengen nonton film atau semacamnya."},
      {jp:"パン<b class='ph'>とか</b>かいてきて。",id:"Beliin roti atau apa gitu ya."}]},
    {sym:"し",r:"shi",kind:"Partikel (接続助詞 / setsuzoku joshi)",
    desc:"Menggabungkan beberapa alasan/fakta. Menyiratkan masih ada alasan lain yang tidak disebutkan.",
    ex:[
      {jp:"やすい<b class='ph'>し</b>、おいしい<b class='ph'>し</b>、いいです。",id:"Murah, enak, pokoknya bagus."},
      {jp:"あめだ<b class='ph'>し</b>、さむい<b class='ph'>し</b>、いきたくない。",id:"Hujan, dingin, pokoknya nggak mau pergi."},
      {jp:"かれはやさしい<b class='ph'>し</b>、かっこいい。",id:"Dia baik hati, lagipula tampan."}]}
  ],
  "Konjungsi Gramatikal (接続助詞)": [
    {sym:"ので",r:"node",kind:"Konjungsi gramatikal (接続助詞)",
    desc:"Menyatakan alasan dengan nada sopan/objektif. Lebih halus dari から.",
    ex:[
      {jp:"あめな<b class='ph'>ので</b>、いきません。",id:"Karena hujan, saya tidak pergi."},
      {jp:"びょうき<b class='ph'>ので</b>、やすみます。",id:"Karena sakit, saya absen."},
      {jp:"じかんがない<b class='ph'>ので</b>、はやくして。",id:"Karena tidak ada waktu, tolong cepat."}]},
    {sym:"のに",r:"noni",kind:"Konjungsi gramatikal (接続助詞)",
    desc:"Menyatakan kontras dengan nuansa kecewa atau tidak terduga. 'Padahal...'",
    ex:[
      {jp:"べんきょうした<b class='ph'>のに</b>、おちた。",id:"Padahal sudah belajar, tetap gagal."},
      {jp:"たかい<b class='ph'>のに</b>、まずい。",id:"Padahal mahal, tapi tidak enak."},
      {jp:"はやくきた<b class='ph'>のに</b>、もうおわった。",id:"Padahal datang lebih awal, sudah selesai."}]},
    {sym:"ながら",r:"nagara",kind:"Partikel penghubung (接続助詞)",
    desc:"Dua aksi berlangsung bersamaan oleh subjek yang sama. 'Sambil ~'",
    ex:[
      {jp:"おんがくをきき<b class='ph'>ながら</b>、べんきょうする。",id:"Belajar sambil mendengarkan musik."},
      {jp:"あるき<b class='ph'>ながら</b>、はなす。",id:"Berbicara sambil berjalan."},
      {jp:"テレビをみ<b class='ph'>ながら</b>、たべる。",id:"Makan sambil nonton TV."}]}
  ],
  "Pola Tata Bahasa (文型)": [
    {sym:"てから",r:"te kara",kind:"Pola tata bahasa (文型)",
    desc:"Gabungan bentuk て + から. Aksi A selesai dulu, baru aksi B. Bukan partikel tunggal.",
    ex:[
      {jp:"しゅくだいを し<b class='ph'>てから</b>、あそぶ。",id:"Setelah mengerjakan PR, baru bermain."},
      {jp:"てをあらっ<b class='ph'>てから</b>、たべる。",id:"Setelah cuci tangan, baru makan."},
      {jp:"そつぎょうし<b class='ph'>てから</b>、はたらく。",id:"Setelah lulus, baru bekerja."}]},
    {sym:"～たり～たり",r:"~tari ~tari",kind:"Pola tata bahasa (文型)",
    desc:"Partikel たり dipakai dua kali untuk memberi contoh aktivitas bergantian/tidak berurutan.",
    ex:[
      {jp:"よんだり かいたり した。",id:"Melakukan hal seperti membaca dan menulis."},
      {jp:"あめがふったり やんだり している。",id:"Hujan kadang turun, kadang berhenti."},
      {jp:"うたったり おどったり たのしんだ。",id:"Bernyanyi, menari, pokoknya bersenang-senang."}]}
  ]
};